# Emit the QSF preservation snippet matching cassette_read_stp.tcl's watch list.
# ALL 70 taps are registers -> PRESERVE_REGISTER only. The bit-bang lines are
# tapped at the REGISTERED seccart latch d_q (not the folded x76f100 input pins:
# Quartus 17.0 rejects `KEEP ON` in the QSF -- Error 125048 -- and a folded comb
# net is fragile). d_q[0]=SDA d_q[1]=SCL d_q[2]=CS d_q[3]=RST d_q[4]=DS2401.
# sda_o (the device output reg) == sec_io0 for an X76F100, so it doubles as the
# seccart readback witness. No comb-node KEEP anywhere -> no 125048 risk.
set SEC  "emu:emu|system573_top:u_s573|s573_seccart:u_seccart"
set EEP  "emu:emu|system573_top:u_s573|s573_seccart:u_seccart|x76f100:eeprom100"

# {name width kind}  kind: reg = PRESERVE_REGISTER (the only kind used now).
set NODES [list \
    [list "$EEP|state"       3 reg ] \
    [list "$EEP|bitc"        4 reg ] \
    [list "$EEP|bytec"       8 reg ] \
    [list "$EEP|command"     8 reg ] \
    [list "$EEP|shift"       8 reg ] \
    [list "$EEP|data_rdata"  8 reg ] \
    [list "$EEP|rd_addr"     7 reg ] \
    [list "$EEP|rd_oob"      1 reg ] \
    [list "$EEP|ram_we"      1 reg ] \
    [list "$EEP|ram_waddr"   7 reg ] \
    [list "$EEP|ram_wdata"   8 reg ] \
    [list "$EEP|pw_ok"       1 reg ] \
    [list "$SEC|d_q"         5 reg ] \
    [list "$EEP|sda_o"       1 reg ] \
]

proc bits {name width} {
    if {$width <= 1} { return [list $name] }
    set r {}
    for {set i 0} {$i < $width} {incr i} { lappend r "${name}\[$i\]" }
    return $r
}

puts "# Generated by gen_qsf.tcl -- DO NOT hand-edit (regenerate to match the watch list)."
puts "set_global_assignment -name ENABLE_SIGNALTAP ON"
puts ""
set nreg 0; set ncomb 0
foreach n $NODES {
    lassign $n name width kind
    puts "# --- [lindex [split $name |] end] ($kind) ---"
    foreach b [bits $name $width] {
        if {$kind eq "reg"} {
            puts "set_instance_assignment -name PRESERVE_REGISTER ON -to \"$b\""
            incr nreg
        } else {
            puts "set_instance_assignment -name KEEP ON -to \"$b\""
            puts "set_instance_assignment -name IMPLEMENT_AS_OUTPUT_OF_LOGIC_CELL ON -to \"$b\""
            incr ncomb
        }
    }
}
puts ""
puts "set_global_assignment -name ENABLE_LOGIC_ANALYZER_INTERFACE ON"
puts stderr "preserved: $nreg registers, $ncomb combinational nodes (total [expr $nreg+$ncomb] bits)"
